### ISSUE TITLE
[FEATURE]: Test with JSONPath Compliance Test Suite

### ISSUE THREAD

**Issue by glyn** [Stillpoint-Software/hyperbee.json#30]
### Tell us about your idea

Would you care to test this implementation against the JSONPath Compliance Test Suite (CTS)?

### Anything else?

Please see https://github.com/jsonpath-standard/jsonpath-compliance-test-suite for the CTS.

See also: https://underlap.org/testing-non-determinism.

**Comment by MattEdwardsWaggleBee** [comment]
I'll take a look.

**Comment by MattEdwardsWaggleBee** [comment]
@glyn Pushed a new release that uses the Compliance Test Suite.  Thank you so much for reaching out and letting us know about these tests.  All the tests pass! :)

**Comment by glyn** [comment]
> @glyn Pushed a new release that uses the Compliance Test Suite. Thank you so much for reaching out and letting us know about these tests. All the tests pass! :)

Congratulations @MattEdwardsWaggleBee! I had a quick squint at what it took and I'm impressed by all the hard work that went in. Well done!
